apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-group5   # Updated name
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mysql-group5
  template:
    metadata:
      labels:
        app: mysql-group5
    spec:
      containers:
      - name: mysql
        image: 899672848368.dkr.ecr.us-east-1.amazonaws.com/flask_db:G5.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        ports:
        - containerPort: 3306
       
